import type { BreathPattern } from "./types.js";

export const PRESETS: BreathPattern[] = [
  {
    id: "box-4-4-4-4",
    name: "Box Breathing",
    slug: "box",
    description:
      "Equal-length inhale, hold, exhale, hold. Used by Navy SEALs and first responders to regulate arousal under stress.",
    phases: { inhale: 4, hold_full: 4, exhale: 4, hold_empty: 4 },
    rounds: 10,
    category: "calm",
    difficulty: "beginner",
    benefits: ["Stress reduction", "Focus", "Parasympathetic activation"],
    contraindications: [],
    source: "Mark Divine, Navy SEALs",
  },
  {
    id: "4-7-8",
    name: "4-7-8 Breathing",
    slug: "4-7-8",
    description:
      "Inhale 4, hold 7, exhale 8. Strong vagal activation. Popularized by Dr. Andrew Weil for sleep and anxiety.",
    phases: { inhale: 4, hold_full: 7, exhale: 8, hold_empty: 0 },
    rounds: 4,
    category: "sleep",
    difficulty: "beginner",
    benefits: ["Sleep onset", "Anxiety relief", "Vagal tone"],
    contraindications: ["Pregnancy (advanced rounds)", "Low blood pressure"],
    source: "Dr. Andrew Weil",
  },
  {
    id: "coherent-5.5",
    name: "Coherent Breathing",
    slug: "coherent",
    description:
      "5.5 breaths per minute (5.5s in, 5.5s out). Maximizes heart-rate variability and resonance.",
    phases: { inhale: 5.5, hold_full: 0, exhale: 5.5, hold_empty: 0 },
    rounds: 22,
    category: "focus",
    difficulty: "beginner",
    benefits: ["HRV", "Resonance", "Calm focus"],
    contraindications: [],
    source: "Stephen Elliott — Coherent Breathing",
  },
  {
    id: "triangle-4-4-4",
    name: "Triangle Breathing",
    slug: "triangle",
    description: "Inhale, hold, exhale — three equal phases. Gentle starter.",
    phases: { inhale: 4, hold_full: 4, exhale: 4, hold_empty: 0 },
    rounds: 10,
    category: "calm",
    difficulty: "beginner",
    benefits: ["Centering", "Beginner-friendly"],
    contraindications: [],
  },
  {
    id: "wim-hof",
    name: "Wim Hof Method",
    slug: "wim-hof",
    description:
      "30–40 deep cycles of full inhale + passive exhale, then exhale-hold to capacity, then 15s recovery inhale-hold. 3 rounds.",
    phases: { inhale: 1.5, hold_full: 0, exhale: 1.5, hold_empty: 0 },
    rounds: 3,
    hyperventilationCycles: 30,
    recoveryHoldEmpty: 15,
    category: "performance",
    difficulty: "advanced",
    benefits: ["Energy", "Alkalinity", "Stress resilience"],
    contraindications: [
      "NEVER practice in or near water",
      "NEVER while driving",
      "Pregnancy",
      "Epilepsy",
      "Cardiovascular disease",
      "Recent surgery",
    ],
    source: "Wim Hof",
  },
  {
    id: "bhastrika",
    name: "Bhastrika (Bellows)",
    slug: "bhastrika",
    description:
      "Rapid, forceful inhales and exhales through the nose. Energizing pranayama.",
    phases: { inhale: 0.5, hold_full: 0, exhale: 0.5, hold_empty: 0 },
    rounds: 30,
    category: "energize",
    difficulty: "intermediate",
    benefits: ["Alertness", "Heat", "Detox"],
    contraindications: [
      "Hypertension",
      "Heart disease",
      "Pregnancy",
      "Recent abdominal surgery",
    ],
    source: "Traditional pranayama",
  },
  {
    id: "nadi-shodhana",
    name: "Nadi Shodhana (Alternate Nostril)",
    slug: "nadi-shodhana",
    description: "Alternate-nostril breathing. Balances nervous system.",
    phases: { inhale: 4, hold_full: 4, exhale: 4, hold_empty: 0 },
    rounds: 12,
    category: "pranayama",
    difficulty: "intermediate",
    benefits: ["Balance", "Calm focus", "Nervous-system regulation"],
    contraindications: [],
    source: "Traditional pranayama",
  },
  {
    id: "physiological-sigh",
    name: "Physiological Sigh",
    slug: "physiological-sigh",
    description:
      "Double inhale through the nose, long exhale through the mouth. Fast stress reset (Huberman Lab).",
    phases: { inhale: 2, hold_full: 0, exhale: 6, hold_empty: 0 },
    rounds: 5,
    category: "calm",
    difficulty: "beginner",
    benefits: ["Rapid CO2 offload", "Stress reset"],
    contraindications: [],
    source: "Andrew Huberman / Stanford",
  },
  {
    id: "buteyko-light",
    name: "Buteyko Light Breathing",
    slug: "buteyko",
    description:
      "Reduced-volume nasal breathing to raise CO2 tolerance. Long gentle phases.",
    phases: { inhale: 4, hold_full: 0, exhale: 6, hold_empty: 2 },
    rounds: 15,
    category: "performance",
    difficulty: "intermediate",
    benefits: ["CO2 tolerance", "Asthma support", "Nasal breathing"],
    contraindications: ["Acute respiratory distress"],
    source: "Konstantin Buteyko",
  },
  {
    id: "tactical-4-4-4-4",
    name: "Tactical Breathing",
    slug: "tactical",
    description: "Military variant of box. Used pre-mission to lower arousal.",
    phases: { inhale: 4, hold_full: 4, exhale: 4, hold_empty: 4 },
    rounds: 8,
    category: "focus",
    difficulty: "beginner",
    benefits: ["Arousal control", "Pre-performance"],
    contraindications: [],
  },
];

export function getPreset(id: string): BreathPattern | undefined {
  return PRESETS.find((p) => p.id === id);
}
